apiVersion: v1
kind: Pod
metadata:
  name: pod-test-multi-configmap
spec:
  containers:
    - name: container-busybox
      image: k8s.gcr.io/busybox
      command: ["/bin/sh","-c","env"]
      # untuk melakukan binding / mapping dari ConfigMap Kubernets ke Container
      env:
        - name: DATA_EXAMPLE      
          valueFrom:
            configMapKeyRef:
              name: data-configmap
              key: DATA_CONTOH
        - name: SPECIAL_CHARACTER
          valueFrom:
            configMapKeyRef:
              name: special-configmap
              key: CHARACTER
  restartPolicy: Never 
